name: Verify Hexnity ID
on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Ensure Title is ONLY Task ID
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This regex matches exactly HEX followed by a dash and numbers, and nothing else
          types: |
            HEX-\d+
          # We disable other parts to enforce the "Title Only" rule
          subjectPattern: ^$ 
          requireScope: false